version: "3.9"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./prisma:/app/prisma
      - ./dev.db:/app/dev.db
    command: sh -c "npx prisma migrate deploy && npx prisma generate && node dist/main.js"
